distribuidora/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from productos.views import ProductListView
from django.urls import include
from django.conf.urls.static import static 
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', ProductListView.as_view() , name='index'),
    path('usuarios/login' , views.login_views, name='login'),
    path('usuarios/logout' , views.logout_views, name='logout'),
    path('usuarios/registro', views.registro , name="registro"),
    path('productos/', include('productos.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

productos/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('search', views.ProductSearchListView.as_view() , name="search"),
    path('<slug:slug>', views.ProductDetailView.as_view(), name='product'),
]

productos/models.py
from django.db import models
from django.utils.text import slugify
from django.db.models.signals import pre_save
import uuid

class Product(models.Model):
    tittle = models.CharField(max_length=50)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0.0)
    slug = models.SlugField(null=False,blank=False, unique=True)
    image = models.ImageField(upload_to='products/' , null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.tittle

def set_slug(sender, instance, *args, **kwargs):
    if instance.tittle and not instance.slug:
        slug = slugify(instance.tittle)
        
        while Product.objects.filter(slug=slug).exists():
            slug = slugify(
                '{}-{}'.format(instance.tittle,str(uuid.uuid4())[:8])
            )
        instance.slug = slug
    
pre_save.connect(set_slug , sender=Product)
            
        

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    
    def get_full_name(self):
        return '{} {}'.format(self.first_name , self.last_name)
     
class Customer(User): 
    class Meta:
        proxy = True 

    def get_products(self): 
        return []
    
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE) 
    bio = models.TextField()

distribuidora/forms.py
from django import forms 
from django.contrib.auth.models import User 

class RegisterForm(forms.Form):
    username =forms.CharField(min_length=5,max_length=20,required=True,
                                    widget=forms.TextInput(attrs={
                                    'class':'form-control',
                                    'id':'username',
                                    'placeholder':'username'
                               }))
    
    email = forms.EmailField(required=True,
                                    widget=forms.EmailInput(attrs={
                                    'class':'form-control',
                                    'id':'email',
                                    'placeholder':'ejemplo@gmail.com'
                               }))
    
    password = forms.CharField(min_length=8, max_length=20, required=True,
                                     widget=forms.PasswordInput(attrs={
                                    'class':'form-control',
                                    'id':'password',
                                    'placeholder':'***********'
                               }))
    
    password2 = forms.CharField(label="Confirmar password", min_length=8, max_length=20, required=True,
                                     widget=forms.PasswordInput(attrs={
                                    'class':'form-control',
                                    'id':'password2',
                                    'placeholder':'***********'
                               }))
    
    
    def clean_username(self):
        username = self.cleaned_data.get('username')
        
        if User.objects.filter(username= username).exists():
            raise forms.ValidationError('El usuario ya se encuentra en uso')
        return username
    
    def clean_email(self):
        email = self.cleaned_data.get('email')
        
        if User.objects.filter(email= email).exists():
            raise forms.ValidationError('El usuario ya se encuentra en uso')
        return email
    
    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data.get('password2') != cleaned_data.get('password'):
            self.add_error('password2' , 'El password no coincide')
    
    def save(self):
        return User.objects.create_user(
            self.cleaned_data.get('username'),
            self.cleaned_data.get('email'),
            self.cleaned_data.get('password'),
            
        )
    
    
    
    
    
    
    
    
    
    

    

distribuidora/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth import authenticate
from django.contrib.auth import login
from django.contrib.auth import logout
from django.contrib import messages
from .forms import RegisterForm
from users.models import User


def index(request):
    return render(request, 'index.html' , {
        'message': 'Listado de productos',
        'products':'Destacados de la semana'
    })
    
    
def login_views(request):
    if request.user.is_authenticated:
        return redirect('index')
    
    if request.method == 'POST':
        username = request.POST.get('username') 
        password = request.POST.get('password')
        
        user = authenticate(username=username , password = password)
        if user:
            login(request, user)
            messages.success(request, 'Bienvenido {}'.format(user.username))
            return redirect('index')
        else:
            messages.error(request, 'El username o password son incorrectos')
    return render(request, 'login.html', {
        
    })

def logout_views(request):
    logout(request)
    messages.success(request, 'sesión cerrada con exito')
    return redirect('login')
    

def registro(request):
    if request.user.is_authenticated:
        return redirect('index')

    form = RegisterForm(request.POST or None)
    if request.method=='POST' and form.is_valid():
        user = form.save()
        if user:
            login(request, user)
            messages.success(request, 'Creado exitosamente')
            return redirect('index')
    
    return render(request, 'registro.html', {
        'form':form
    })

productos/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from .models import Product
from django.views.generic.detail import DetailView

class ProductListView(ListView):
    template_name = 'index.html'
    queryset = Product.objects.all().order_by('-id')
   
class ProductDetailView(DetailView):
    model = Product 
    template_name = 'product.html'
    
class ProductSearchListView(ListView):
    template_name= 'search.html'
    
    def get_queryset(self):
        return Product.objects.filter(tittle__icontains=self.query())
    
    def query(self):
        return self.request.GET.get('q')
    
    def get_content_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.query()
        context['count'] = context['product_list'].count()

        return context 

users/views.py
from django.shortcuts import render

# Create your views here.

productos/templates/product.html
{% extends 'base.html' %}

{% block content %}

<div class="col-3">
    {% if product.image %}
        <img src="{{product.image.url}}" alt="Imagen del producto" width="200" height="200">
    {% endif %}
</div>

<div class="col">
    <div class="h1"> {{product.tittle}}</div>
    <div class="h5 font-weight-bold"> Precio: <span class="text-success">${{product.price}}</span></div>
    <div class="">{{product.description}}</div>
</div>

{% endblock %}

productos/templates/search.html
{% extends 'base.html' %}

{% block content %}

<div class="col">
    {% include 'snippets/search.html' with query=query %}

    <hr>
    <p>Resultados para: {{query}} ({{count}})</p>
    {% include 'snippets/list.html' %}
    </div>
    

</div>

{% endblock %}

productos/templates/snippets/list.html
<div class="row">

    {% for object in product_list %}

    <div class="col-3 mt-5">
        {% include 'snippets/product.html' with product=object %}
    </div>

    {% endfor %}

</div>

productos/templates/snippets/product.html
<div class="card h-100">
    {% if product.image %}

    <img src="{{product.image.url}}" alt="Imagen del producto" height="300">

    {% endif %}
    <div class="card-body">
        <h5 class="card-tittle">{{product.tittle}}</h5>
        <p class="card-text">{{product.description}}</p>
        <a class="btn btn-primary" href="{% url 'products:product' product.slug %}">Ver mas</a>
    </div>
</div>

productos/templates/snippets/search.html
<form action="{% url 'products:search' %}">
    <div class="input-group">
        <input type="text" name="q" value="{{query}}" class="form-control" placeholder="Buscar">
        <div class=".input-group-append" >
            <input type="submit" name="" value="Buscar" class="btn btn-primary">
        </div>
    </div>
</form>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://kit.fontawesome.com/7ff6d8d913.css" crossorigin="anonymous">
    <title>Distribuidora Rinaldi</title>
</head>
<body>


    {% include 'navbar.html' %}
<div class="container">
    {% include 'messages.html' %}

    
<div class="row mt-3">
    {% block content %}
    {% endblock %}

</div>
</div>
</body>
<script src="https://kit.fontawesome.com/7ff6d8d913.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
</html>

templates/index.html
{%extends 'base.html'%}

{%block content%}

<div class="col">
    <h4 class="text-center"> {{message}}</h4>
    {% include 'snippets/search.html'%}
    {% include 'snippets/list.html' %}
</div>


{%endblock%}


templates/login.html
{%extends 'base.html'%}

{%block content%}

<div class="container my-5">
    <div class="row">
        <div class="col">
            <h1 class="h1 text-center">Login</h1>
            <form action="" method='POST'>
                {% csrf_token %}
                <div>
                    <label for="username" class='form-label'>Username</label>
                    <input type="text" name="username" id="username" class='form-control'>
                </div>
                <div>
                    <label for="password" class='form-label'>Password</label>
                    <input type="text" name="password" id="password" class='form-control'>
                </div>
            <button type='submit' name='button' class='btn btn-primary'>Ingresar</button>
            </form>
        </div>
    </div>
</div>



{%endblock%}

templates/messages.html
{% if messages %}
        {% for message in messages %}
            {% if message.tags == 'success' %}
            <div class="alert alert-success">
                {{message}}
                <button type="button" class="close" data-dismiss="alert">x</button>
            </div>
            {% else %}
            <div class="alert alert-danger">
                {{message}}
                <button type="button" class="close" data-dismiss="alert">x</button>
            </div>
            {% endif %}
        {% endfor %}
    {% endif %}

templates/navbar.html
{% url 'login' as login %} 
{% url 'registro' as registro %} 
{% url 'index' as index %} 


<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'index' %}">HOME</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">

            {% if user.is_authenticated %}

              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">
                    <span class="fa-solid fa-arrow-right-from-bracket"></span> 
                    Cerrar sesión</a>
              </li>

            {% else %}
            <li class="nav-item {% if request.path == login %} active {% endif %}">
                <a class="nav-link" href="{{login}}">
                    <span class="fas fa-user"></span>  
                    Iniciar sesión</a>
            </li>
            <li class="nav-item {% if request.path == registro %} active {% endif %}">
                <a class="nav-link" href=" {{registro}}">
                    <span class="fas fa-user-plus"></span> Registrarse</a>
            </li>
         {% endif %}
        </ul>
      </div>
    </div>
  </nav>

templates/registro.html
{%extends 'base.html'%}

{%block content%}

<div class="container">
    <div class="row">
        <div class="col">
            <h1 class="h1 text-center">Registrarse</h1>
            <div class="container">
                <div class="row">
                    <div class="col">
                        <h2>Registro</h2>
            
                    <form method="POST">
                        {% csrf_token %}
                        {{form}}
                        <button type="submit" name="button" class="btn btn-primary">Registrar</button>
                    </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



{%endblock%}